/**
 * Domínio de APACs — espelha os enums do contrato em `.docs/api-backend.md`.
 *
 * `erasableSyntaxOnly` proíbe `enum`, então os valores vivem em `const objects`
 * e os tipos são derivados deles.
 */

export const APAC_STATUS = {
  PENDENTE: "PENDENTE",
  AGUARDO: "AGUARDO",
  APROVADO: "APROVADO",
  CANCELADO: "CANCELADO",
  NEGADO: "NEGADO",
  ENTREGUE: "ENTREGUE",
} as const

export type ApacStatus = (typeof APAC_STATUS)[keyof typeof APAC_STATUS]

/**
 * Catálogo fixo de procedimentos aceitos pela API — ela garante isso com um
 * enum interno do Prisma. As chaves são o valor que viaja no `POST`/`PATCH`
 * (`SCREAMING_SNAKE_CASE`, sem acento); o texto formatado é só para exibição,
 * ver `APAC_PROCEDURE_LABEL`. Lista grande demais para um `Select` comum; nos
 * formulários é um `Combobox` com busca.
 */
export const APAC_PROCEDURE = {
  CONSULTA_EM_ALERGIA_E_IMUNOLOGIA_PEDIATRICA: "CONSULTA_EM_ALERGIA_E_IMUNOLOGIA_PEDIATRICA",
  CONSULTA_EM_ODONTOLOGIA_CIRURGIA_BUCO_MAXILO_FACIAL: "CONSULTA_EM_ODONTOLOGIA_CIRURGIA_BUCO_MAXILO_FACIAL",
  CONSULTA_EM_CIRURGIA_DE_CABECA_E_PESCOCO: "CONSULTA_EM_CIRURGIA_DE_CABECA_E_PESCOCO",
  OCI_AVALIACAO_CARDIOLOGICA: "OCI_AVALIACAO_CARDIOLOGICA",
  CONSULTA_EM_DERMATOLOGIA_ADULTO: "CONSULTA_EM_DERMATOLOGIA_ADULTO",
  CONSULTA_EM_ENDOCRINOLOGIA_E_METABOLOGIA: "CONSULTA_EM_ENDOCRINOLOGIA_E_METABOLOGIA",
  CONSULTA_EM_GASTROENTEROLOGIA_GERAL: "CONSULTA_EM_GASTROENTEROLOGIA_GERAL",
  CONSULTA_EM_GINECOLOGIA: "CONSULTA_EM_GINECOLOGIA",
  CONSULTA_EM_HEMATOLOGIA: "CONSULTA_EM_HEMATOLOGIA",
  CONSULTA_EM_HEPATOLOGIA: "CONSULTA_EM_HEPATOLOGIA",
  CONSULTA_EM_INFECTOLOGIA: "CONSULTA_EM_INFECTOLOGIA",
  CONSULTA_EM_MASTOLOGIA_GERAL: "CONSULTA_EM_MASTOLOGIA_GERAL",
  CONSULTA_EM_MASTOLOGIA_CIRURGIA: "CONSULTA_EM_MASTOLOGIA_CIRURGIA",
  CONSULTA_EM_NEFROLOGIA_PRE_DIALITICO: "CONSULTA_EM_NEFROLOGIA_PRE_DIALITICO",
  CONSULTA_EM_NEUROCIRURGIA_ADULTO: "CONSULTA_EM_NEUROCIRURGIA_ADULTO",
  CONSULTA_EM_NEUROLOGIA_CLINICA: "CONSULTA_EM_NEUROLOGIA_CLINICA",
  CONSULTA_EM_PRE_NATAL_DE_ALTO_RISCO: "CONSULTA_EM_PRE_NATAL_DE_ALTO_RISCO",
  OCI_AVALIACAO_INICIAL_EM_OFTALMOLOGIA_A_PARTIR_DE_9_ANOS: "OCI_AVALIACAO_INICIAL_EM_OFTALMOLOGIA_A_PARTIR_DE_9_ANOS",
  CONSULTA_EM_ONCOLOGIA_CLINICA: "CONSULTA_EM_ONCOLOGIA_CLINICA",
  OCI_AVALIACAO_DIAGNOSTICA_EM_ORTOPEDIA_COM_RECURSOS_DE_RADIOLOGIA:
    "OCI_AVALIACAO_DIAGNOSTICA_EM_ORTOPEDIA_COM_RECURSOS_DE_RADIOLOGIA",
  CONSULTA_EM_OTORRINOLARINGOLOGIA: "CONSULTA_EM_OTORRINOLARINGOLOGIA",
  OCI_AVALIACAO_INICIAL_DIAGNOSTICA_DE_DEFICIT_AUDITIVO: "OCI_AVALIACAO_INICIAL_DIAGNOSTICA_DE_DEFICIT_AUDITIVO",
  OCI_AVALIACAO_DIAGNOSTICA_DE_NASORAFINGE_E_DE_OROFARINGE: "OCI_AVALIACAO_DIAGNOSTICA_DE_NASORAFINGE_E_DE_OROFARINGE",
  CONSULTA_EM_CIRURGIA_PLASTICA: "CONSULTA_EM_CIRURGIA_PLASTICA",
  CONSULTA_EM_PNEUMOLOGIA: "CONSULTA_EM_PNEUMOLOGIA",
  CONSULTA_EM_PROCTOLOGIA: "CONSULTA_EM_PROCTOLOGIA",
  CONSULTA_EM_PSIQUIATRIA: "CONSULTA_EM_PSIQUIATRIA",
  CONSULTA_EM_REUMATOLOGIA: "CONSULTA_EM_REUMATOLOGIA",
  CONSULTA_EM_UROLOGIA: "CONSULTA_EM_UROLOGIA",
  CONSULTA_EM_PEDIATRIA: "CONSULTA_EM_PEDIATRIA",
  CONSULTA_EM_CARDIOLOGIA_PEDIATRIA: "CONSULTA_EM_CARDIOLOGIA_PEDIATRIA",
  CONSULTA_EM_DERMATOLOGIA_PEDIATRIA: "CONSULTA_EM_DERMATOLOGIA_PEDIATRIA",
  CONSULTA_EM_ENDOCRINOLOGIA_E_METABOLOGIA_PEDIATRIA: "CONSULTA_EM_ENDOCRINOLOGIA_E_METABOLOGIA_PEDIATRIA",
  CONSULTA_EM_GASTROENTEROLOGIA_PEDIATRIA: "CONSULTA_EM_GASTROENTEROLOGIA_PEDIATRIA",
  CONSULTA_EM_GINECOLOGIA_PEDIATRIA: "CONSULTA_EM_GINECOLOGIA_PEDIATRIA",
  CONSULTA_EM_HEMATOLOGIA_PEDIATRIA: "CONSULTA_EM_HEMATOLOGIA_PEDIATRIA",
  CONSULTA_EM_HEPATOLOGIA_PEDIATRIA: "CONSULTA_EM_HEPATOLOGIA_PEDIATRIA",
  CONSULTA_EM_NEFROLOGIA_PEDIATRIA: "CONSULTA_EM_NEFROLOGIA_PEDIATRIA",
  CONSULTA_EM_NEUROCIRURGIA_PEDIATRIA: "CONSULTA_EM_NEUROCIRURGIA_PEDIATRIA",
  CONSULTA_EM_NEUROLOGIA_PEDIATRIA: "CONSULTA_EM_NEUROLOGIA_PEDIATRIA",
  OCI_AVALIACAO_INICIAL_EM_OFTALMOLOGIA_0_A_8_ANOS: "OCI_AVALIACAO_INICIAL_EM_OFTALMOLOGIA_0_A_8_ANOS",
  CONSULTA_EM_ORTOPEDIA_GERAL_PEDIATRIA: "CONSULTA_EM_ORTOPEDIA_GERAL_PEDIATRIA",
  CONSULTA_EM_OTORRINOLARINGOLOGIA_PEDIATRICA: "CONSULTA_EM_OTORRINOLARINGOLOGIA_PEDIATRICA",
  CONSULTA_EM_PNEUMOLOGIA_PEDIATRIA: "CONSULTA_EM_PNEUMOLOGIA_PEDIATRIA",
  CONSULTA_EM_PSIQUIATRIA_PEDIATRIA: "CONSULTA_EM_PSIQUIATRIA_PEDIATRIA",
  CONSULTA_EM_CARDIOLOGIA_CARDIOPATIA_CONGENITA: "CONSULTA_EM_CARDIOLOGIA_CARDIOPATIA_CONGENITA",
  CONSULTA_EM_CIRURGIA_PEDIATRICA: "CONSULTA_EM_CIRURGIA_PEDIATRICA",
} as const

export type ApacProcedure = (typeof APAC_PROCEDURE)[keyof typeof APAC_PROCEDURE]

export const APAC_PRIORITY = {
  URGENTE: "URGENTE",
  ELETIVO: "ELETIVO",
} as const

export type ApacPriority = (typeof APAC_PRIORITY)[keyof typeof APAC_PRIORITY]

export const APAC_ACS = {
  MARLON: "MARLON",
  MARIA_JOSE_SILVA_RIBEIRO: "MARIA_JOSE_SILVA_RIBEIRO",
  MARIA_JOSE_DE_ARAUJO: "MARIA_JOSE_DE_ARAUJO",
  MARIA_DE_LOURDES: "MARIA_DE_LOURDES",
  MANOEL_BATISTA: "MANOEL_BATISTA",
  LEYDIANE_ARAUJO: "LEYDIANE_ARAUJO",
  KAIO_VICTOR: "KAIO_VICTOR",
  JOAO_MANOEL: "JOAO_MANOEL",
  ELANE_CRISTINA: "ELANE_CRISTINA",
  EDILEUZA_ALVES: "EDILEUZA_ALVES",
  ANA_EMILIA: "ANA_EMILIA",
  DEYSE: "DEYSE",
  JOELMA_FERNANDES: "JOELMA_FERNANDES",
  FLAVIO: "FLAVIO",
} as const

export type ApacAcs = (typeof APAC_ACS)[keyof typeof APAC_ACS]

export const USER_ROLE = {
  DEV: "DEV",
  DIRETOR: "DIRETOR",
  SECRETARIA: "SECRETARIA",
  RECEPCIONISTA: "RECEPCIONISTA",
  REGULADOR: "REGULADOR",
} as const

export type UserRole = (typeof USER_ROLE)[keyof typeof USER_ROLE]

export const APAC_STATUS_LABEL: Record<ApacStatus, string> = {
  PENDENTE: "Pendente",
  AGUARDO: "Em análise",
  APROVADO: "Aprovada",
  CANCELADO: "Cancelada",
  NEGADO: "Negada",
  ENTREGUE: "Entregue",
}

/** Variante de `Badge` usada para cada status — só tokens semânticos. */
export const APAC_STATUS_BADGE: Record<ApacStatus, "default" | "secondary" | "destructive" | "outline"> = {
  PENDENTE: "outline",
  AGUARDO: "secondary",
  APROVADO: "default",
  CANCELADO: "outline",
  NEGADO: "destructive",
  ENTREGUE: "default",
}

export const APAC_PRIORITY_LABEL: Record<ApacPriority, string> = {
  URGENTE: "Urgente",
  ELETIVO: "Eletivo",
}

/** Texto formatado para exibição — a chave do enum é `SCREAMING_SNAKE_CASE` sem acento. */
export const APAC_PROCEDURE_LABEL: Record<ApacProcedure, string> = {
  CONSULTA_EM_ALERGIA_E_IMUNOLOGIA_PEDIATRICA: "CONSULTA EM ALERGIA E IMUNOLOGIA - PEDIATRICA",
  CONSULTA_EM_ODONTOLOGIA_CIRURGIA_BUCO_MAXILO_FACIAL: "CONSULTA EM ODONTOLOGIA - CIRURGIA BUCO-MAXILO FACIAL",
  CONSULTA_EM_CIRURGIA_DE_CABECA_E_PESCOCO: "CONSULTA EM CIRURGIA DE CABECA E PESCOCO",
  OCI_AVALIACAO_CARDIOLOGICA: "OCI AVALIAÇÃO CARDIOLÓGICA",
  CONSULTA_EM_DERMATOLOGIA_ADULTO: "CONSULTA EM DERMATOLOGIA - ADULTO",
  CONSULTA_EM_ENDOCRINOLOGIA_E_METABOLOGIA: "CONSULTA EM ENDOCRINOLOGIA E METABOLOGIA",
  CONSULTA_EM_GASTROENTEROLOGIA_GERAL: "CONSULTA EM GASTROENTEROLOGIA - GERAL",
  CONSULTA_EM_GINECOLOGIA: "CONSULTA EM GINECOLOGIA",
  CONSULTA_EM_HEMATOLOGIA: "CONSULTA EM HEMATOLOGIA",
  CONSULTA_EM_HEPATOLOGIA: "CONSULTA EM HEPATOLOGIA",
  CONSULTA_EM_INFECTOLOGIA: "CONSULTA EM INFECTOLOGIA",
  CONSULTA_EM_MASTOLOGIA_GERAL: "CONSULTA EM MASTOLOGIA - GERAL",
  CONSULTA_EM_MASTOLOGIA_CIRURGIA: "CONSULTA EM MASTOLOGIA - CIRURGIA",
  CONSULTA_EM_NEFROLOGIA_PRE_DIALITICO: "CONSULTA EM NEFROLOGIA - PRE DIALITICO",
  CONSULTA_EM_NEUROCIRURGIA_ADULTO: "CONSULTA EM NEUROCIRURGIA ADULTO",
  CONSULTA_EM_NEUROLOGIA_CLINICA: "CONSULTA EM NEUROLOGIA - CLINICA",
  CONSULTA_EM_PRE_NATAL_DE_ALTO_RISCO: "CONSULTA EM PRE-NATAL DE ALTO RISCO",
  OCI_AVALIACAO_INICIAL_EM_OFTALMOLOGIA_A_PARTIR_DE_9_ANOS:
    "OCI AVALIAÇÃO INICIAL EM OFTALMOLOGIA - A PARTIR DE 9 ANOS",
  CONSULTA_EM_ONCOLOGIA_CLINICA: "CONSULTA EM ONCOLOGIA CLINICA",
  OCI_AVALIACAO_DIAGNOSTICA_EM_ORTOPEDIA_COM_RECURSOS_DE_RADIOLOGIA:
    "OCI - AVALIAÇÃO DIAGNÓSTICA EM ORTOPEDIA COM RECURSOS DE RADIOLOGIA",
  CONSULTA_EM_OTORRINOLARINGOLOGIA: "CONSULTA EM OTORRINOLARINGOLOGIA",
  OCI_AVALIACAO_INICIAL_DIAGNOSTICA_DE_DEFICIT_AUDITIVO: "OCI - AVALIAÇÃO INICIAL DIAGNÓSTICA DE DEFICIT AUDITIVO",
  OCI_AVALIACAO_DIAGNOSTICA_DE_NASORAFINGE_E_DE_OROFARINGE:
    "OCI - AVALIAÇÃO DIAGNÓSTICA DE NASORAFINGE E DE OROFARINGE",
  CONSULTA_EM_CIRURGIA_PLASTICA: "CONSULTA EM CIRURGIA PLASTICA",
  CONSULTA_EM_PNEUMOLOGIA: "CONSULTA EM PNEUMOLOGIA",
  CONSULTA_EM_PROCTOLOGIA: "CONSULTA EM PROCTOLOGIA",
  CONSULTA_EM_PSIQUIATRIA: "CONSULTA EM PSIQUIATRIA",
  CONSULTA_EM_REUMATOLOGIA: "CONSULTA EM REUMATOLOGIA",
  CONSULTA_EM_UROLOGIA: "CONSULTA EM UROLOGIA",
  CONSULTA_EM_PEDIATRIA: "CONSULTA EM PEDIATRIA",
  CONSULTA_EM_CARDIOLOGIA_PEDIATRIA: "CONSULTA EM CARDIOLOGIA - PEDIATRIA",
  CONSULTA_EM_DERMATOLOGIA_PEDIATRIA: "CONSULTA EM DERMATOLOGIA - PEDIATRIA",
  CONSULTA_EM_ENDOCRINOLOGIA_E_METABOLOGIA_PEDIATRIA: "CONSULTA EM ENDOCRINOLOGIA E METABOLOGIA - PEDIATRIA",
  CONSULTA_EM_GASTROENTEROLOGIA_PEDIATRIA: "CONSULTA EM GASTROENTEROLOGIA - PEDIATRIA",
  CONSULTA_EM_GINECOLOGIA_PEDIATRIA: "CONSULTA EM GINECOLOGIA - PEDIATRIA",
  CONSULTA_EM_HEMATOLOGIA_PEDIATRIA: "CONSULTA EM HEMATOLOGIA - PEDIATRIA",
  CONSULTA_EM_HEPATOLOGIA_PEDIATRIA: "CONSULTA EM HEPATOLOGIA - PEDIATRIA",
  CONSULTA_EM_NEFROLOGIA_PEDIATRIA: "CONSULTA EM NEFROLOGIA - PEDIATRIA",
  CONSULTA_EM_NEUROCIRURGIA_PEDIATRIA: "CONSULTA EM NEUROCIRURGIA - PEDIATRIA",
  CONSULTA_EM_NEUROLOGIA_PEDIATRIA: "CONSULTA EM NEUROLOGIA - PEDIATRIA",
  OCI_AVALIACAO_INICIAL_EM_OFTALMOLOGIA_0_A_8_ANOS: "OCI - AVALIAÇÃO INICIAL EM OFTALMOLOGIA - 0 A 8 ANOS",
  CONSULTA_EM_ORTOPEDIA_GERAL_PEDIATRIA: "CONSULTA EM ORTOPEDIA GERAL - PEDIATRIA",
  CONSULTA_EM_OTORRINOLARINGOLOGIA_PEDIATRICA: "CONSULTA EM OTORRINOLARINGOLOGIA PEDIATRICA",
  CONSULTA_EM_PNEUMOLOGIA_PEDIATRIA: "CONSULTA EM PNEUMOLOGIA - PEDIATRIA",
  CONSULTA_EM_PSIQUIATRIA_PEDIATRIA: "CONSULTA EM PSIQUIATRIA - PEDIATRIA",
  CONSULTA_EM_CARDIOLOGIA_CARDIOPATIA_CONGENITA: "CONSULTA EM CARDIOLOGIA - CARDIOPATIA CONGENITA",
  CONSULTA_EM_CIRURGIA_PEDIATRICA: "CONSULTA EM CIRURGIA PEDIATRICA",
}

/** Nome de exibição de cada ACS — o enum usa nome em `SCREAMING_SNAKE_CASE`. */
export const APAC_ACS_LABEL: Record<ApacAcs, string> = {
  MARLON: "Marlon",
  MARIA_JOSE_SILVA_RIBEIRO: "Maria José Silva Ribeiro",
  MARIA_JOSE_DE_ARAUJO: "Maria José de Araújo",
  MARIA_DE_LOURDES: "Maria de Lourdes",
  MANOEL_BATISTA: "Manoel Batista",
  LEYDIANE_ARAUJO: "Leydiane Araújo",
  KAIO_VICTOR: "Kaio Victor",
  JOAO_MANOEL: "João Manoel",
  ELANE_CRISTINA: "Elane Cristina",
  EDILEUZA_ALVES: "Edileuza Alves",
  ANA_EMILIA: "Ana Emília",
  DEYSE: "Deyse",
  JOELMA_FERNANDES: "Joelma Fernandes",
  FLAVIO: "Flávio",
}

export const USER_ROLE_LABEL: Record<UserRole, string> = {
  DEV: "Desenvolvedor",
  DIRETOR: "Diretor Geral",
  SECRETARIA: "Secretária de Saúde",
  RECEPCIONISTA: "Recepcionista",
  REGULADOR: "Regulador",
}

export const APAC_STATUS_LIST = Object.values(APAC_STATUS)
export const APAC_PRIORITY_LIST = Object.values(APAC_PRIORITY)
export const APAC_PROCEDURE_LIST = Object.values(APAC_PROCEDURE)
export const APAC_ACS_LIST = Object.values(APAC_ACS)
export const USER_ROLE_LIST = Object.values(USER_ROLE)

/**
 * Shape `{ value, label }` — o `Combobox` (Base UI) reconhece esse formato
 * automaticamente e usa `label` pra exibir/buscar e `value` pro valor
 * selecionado, sem precisar de `itemToStringLabel`/`itemToStringValue`.
 */
export const APAC_PROCEDURE_OPTIONS = APAC_PROCEDURE_LIST.map((value) => ({
  value,
  label: APAC_PROCEDURE_LABEL[value],
}))

/** Iniciais para `AvatarFallback` — no máximo duas letras. */
export function getInitials(name: string) {
  const parts = name.trim().split(/\s+/)
  const first = parts.at(0)?.charAt(0) ?? ""
  const last = parts.length > 1 ? (parts.at(-1)?.charAt(0) ?? "") : ""

  return `${first}${last}`.toUpperCase()
}
